services:
  mysql:
    image: mysql:latest
    container_name: mintyMysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=minty
    volumes:
      - mintyData:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped
    healthcheck: 
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5
  
  backend:
    build:
      ./
    container_name: mintyBackend
    ports:
      - "8000:8000"
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
  
  frontend:
    build: ./MintyMovies/
    container_name: MintyMovies
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_started

networks:
  app-network:
volumes:
  mintyData: